package online.timefiles.vantaloom

import android.content.Context
import android.webkit.JavascriptInterface
import org.json.JSONObject
import java.util.concurrent.Executors

/**
 * The native half of window.__loomBridge (docs/loomnet-design.md §8.1), exposed to
 * the WebView via addJavascriptInterface as `window.__loomNative`. A thin JS shim
 * (injected at document start by MainActivity) adapts these primitive-only methods
 * to the surface the web client consumes.
 *
 * Bridge contract v2 — the web side (loom-bridge.ts) owns the ONLY promise
 * registry. Async methods take a callId (generated by the web) and fulfil it by
 * evaluating back on the WebView:
 *   window.__loomResolve(callId, payloadJsonString)   // "" ⇒ {}
 *   window.__loomReject(callId, errorMessage)
 * They run off the WebView's JavaBridge thread on a single-thread executor so the
 * blocking overlay work never stalls the bridge; sync getters return directly.
 * (v1 had a second registry inside the shim with an incompatible resolver
 * signature — every async call timed out. One registry, one signature, forever.)
 *
 * Deviation from the §8.1 sketch: startNode takes a THIRD arg, machineId — the
 * Hub-assigned machine.id (from device registration), which the overlay uses as
 * its mTLS certificate CN and which the Hub peer list keys on. The sketch omitted
 * it assuming native owns identity, but the Hub assigns machine.id at registration
 * (≠ the device SSAID), so the frontend must supply it.
 */
class LoomJsBridge(
    private val context: Context,
    private val evalJs: (String) -> Unit,
    /** 系统栏配色回调（web 主题 → MainActivity.applyChrome）。 */
    private val onChrome: (color: String, dark: Boolean) -> Unit = { _, _ -> },
) {
    private val worker = Executors.newSingleThreadExecutor()

    @JavascriptInterface
    fun isNative(): Boolean = true

    /** The device hardware id (`android-<ssaid>`), for Hub registration. */
    @JavascriptInterface
    fun deviceId(): String = DeviceId.get(context)

    /** The loopback proxy port, or 0 before StartNode. */
    @JavascriptInterface
    fun loopbackPort(): Int = Loom.get()?.loopbackPort()?.toInt() ?: 0

    /** The connection status JSON ({state,path?,error?}); sync (in-memory). */
    @JavascriptInterface
    fun statusJSON(): String = Loom.get()?.statusJSON() ?: """{"state":"idle"}"""

    /** Rotate the Hub JWT used by the mini Hub client + signaling WS. */
    @JavascriptInterface
    fun setToken(token: String) {
        Loom.get()?.setToken(token)
    }

    /**
     * 系统栏/安全区边条配色：web 主题变化时（native-chrome.ts）推真实背景色 +
     * 明暗过来，壳侧给 WebView 背景与系统栏图标换色。
     */
    @JavascriptInterface
    fun setChrome(backgroundColor: String, dark: Boolean) {
        onChrome(backgroundColor, dark)
    }

    /**
     * Start the overlay node + loopback proxy. Brings up the foreground service so
     * the node survives backgrounding. Idempotent (a second call while running is a
     * no-op inside the facade).
     */
    @JavascriptInterface
    fun startNode(callId: String, hubBaseUrl: String, hubToken: String, machineId: String) {
        worker.execute {
            try {
                LoomForegroundService.start(context)
                val dataDir = context.filesDir.absolutePath
                Loom.ensure().startNode(dataDir, hubBaseUrl, machineId, hubToken)
                resolve(callId, "")
            } catch (e: Throwable) {
                reject(callId, e.message ?: "startNode failed")
            }
        }
    }

    /**
     * Point the loopback at a peer and warm the overlay dial. Resolves with
     * {localUrl:"http://127.0.0.1:<port>"} — the base the web client aims its
     * local-API calls at (setRuntimeTarget).
     */
    @JavascriptInterface
    fun connect(callId: String, machineId: String) {
        worker.execute {
            try {
                val b = Loom.get() ?: throw IllegalStateException("node not started")
                b.connect(machineId)
                val port = b.loopbackPort().toInt()
                val payload = JSONObject().put("localUrl", "http://127.0.0.1:$port").toString()
                resolve(callId, payload)
            } catch (e: Throwable) {
                reject(callId, e.message ?: "connect failed")
            }
        }
    }

    /** Clear the loopback target; the node + cached sessions stay up. */
    @JavascriptInterface
    fun disconnect(callId: String) {
        worker.execute {
            try {
                Loom.get()?.disconnect()
                resolve(callId, "")
            } catch (e: Throwable) {
                reject(callId, e.message ?: "disconnect failed")
            }
        }
    }

    /** Tear the node down and stop the foreground service. */
    @JavascriptInterface
    fun stopNode(callId: String) {
        worker.execute {
            try {
                Loom.get()?.stop()
                LoomForegroundService.stop(context)
                resolve(callId, "")
            } catch (e: Throwable) {
                reject(callId, e.message ?: "stop failed")
            }
        }
    }

    /**
     * Fulfil the web-side promise for callId (contract v2). payloadJson is the
     * raw JSON text of the success value ("" for void) — quote() turns it into a
     * JS string literal; the web JSON.parses it. Defensive `&&`: a page reload
     * can race an in-flight worker task, leaving no resolver installed.
     */
    private fun resolve(callId: String, payloadJson: String) {
        evalJs("window.__loomResolve && window.__loomResolve(${quote(callId)}, ${quote(payloadJson)})")
    }

    private fun reject(callId: String, message: String) {
        evalJs("window.__loomReject && window.__loomReject(${quote(callId)}, ${quote(message)})")
    }

    // JSONObject.quote yields a properly escaped JSON string literal, which is also
    // a valid JS string literal.
    private fun quote(s: String): String = JSONObject.quote(s)
}
