package online.timefiles.vantaloom

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Matrix
import android.media.ExifInterface
import android.net.Uri
import android.util.Base64
import android.webkit.JavascriptInterface
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.util.concurrent.Executors

/**
 * The native half of window.__loomBridge (docs/loomnet-design.md §8.1), exposed to
 * the WebView via addJavascriptInterface as `window.__loomNative`. A thin JS shim
 * (injected at document start by MainActivity) adapts these primitive-only methods
 * to the surface the web client consumes.
 *
 * Bridge contract v2 — the web side (loom-bridge.ts) owns the ONLY promise
 * registry. Async methods take a callId (generated by the web) and fulfil it by
 * evaluating back on the WebView:
 *   window.__loomResolve(callId, payloadJsonString)   // "" ⇒ {}
 *   window.__loomReject(callId, errorMessage)
 * They run off the WebView's JavaBridge thread on a single-thread executor so the
 * blocking overlay work never stalls the bridge; sync getters return directly.
 * (v1 had a second registry inside the shim with an incompatible resolver
 * signature — every async call timed out. One registry, one signature, forever.)
 *
 * Deviation from the §8.1 sketch: startNode takes a THIRD arg, machineId — the
 * Hub-assigned machine.id (from device registration), which the overlay uses as
 * its mTLS certificate CN and which the Hub peer list keys on. The sketch omitted
 * it assuming native owns identity, but the Hub assigns machine.id at registration
 * (≠ the device SSAID), so the frontend must supply it.
 */
class LoomJsBridge(
    private val context: Context,
    private val evalJs: (String) -> Unit,
    /** 系统栏配色回调（web 主题 → MainActivity.applyChrome）。 */
    private val onChrome: (color: String, dark: Boolean) -> Unit = { _, _ -> },
    /** 图片选择回调（composer 加号 → MainActivity 拉起相机/相册）。 */
    private val onPickImages: (callId: String, source: String) -> Unit = { _, _ -> },
) {
    private val worker = Executors.newSingleThreadExecutor()

    @JavascriptInterface
    fun isNative(): Boolean = true

    /** The device hardware id (`android-<ssaid>`), for Hub registration. */
    @JavascriptInterface
    fun deviceId(): String = DeviceId.get(context)

    /** The loopback proxy port, or 0 before StartNode. */
    @JavascriptInterface
    fun loopbackPort(): Int = Loom.get()?.loopbackPort()?.toInt() ?: 0

    /** The connection status JSON ({state,path?,error?}); sync (in-memory). */
    @JavascriptInterface
    fun statusJSON(): String = Loom.get()?.statusJSON() ?: """{"state":"idle"}"""

    /** Rotate the Hub JWT used by the mini Hub client + signaling WS. */
    @JavascriptInterface
    fun setToken(token: String) {
        Loom.get()?.setToken(token)
    }

    /**
     * 系统栏/安全区边条配色：web 主题变化时（native-chrome.ts）推真实背景色 +
     * 明暗过来，壳侧给 WebView 背景与系统栏图标换色。
     */
    @JavascriptInterface
    fun setChrome(backgroundColor: String, dark: Boolean) {
        onChrome(backgroundColor, dark)
    }

    /**
     * Start the overlay node + loopback proxy. Brings up the foreground service so
     * the node survives backgrounding. Idempotent (a second call while running is a
     * no-op inside the facade).
     */
    @JavascriptInterface
    fun startNode(callId: String, hubBaseUrl: String, hubToken: String, machineId: String) {
        worker.execute {
            try {
                LoomForegroundService.start(context)
                val dataDir = context.filesDir.absolutePath
                Loom.ensure().startNode(dataDir, hubBaseUrl, machineId, hubToken)
                resolve(callId, "")
            } catch (e: Throwable) {
                reject(callId, e.message ?: "startNode failed")
            }
        }
    }

    /**
     * Point the loopback at a peer and warm the overlay dial. Resolves with
     * {localUrl:"http://127.0.0.1:<port>"} — the base the web client aims its
     * local-API calls at (setRuntimeTarget).
     */
    @JavascriptInterface
    fun connect(callId: String, machineId: String) {
        worker.execute {
            try {
                val b = Loom.get() ?: throw IllegalStateException("node not started")
                b.connect(machineId)
                val port = b.loopbackPort().toInt()
                val payload = JSONObject().put("localUrl", "http://127.0.0.1:$port").toString()
                resolve(callId, payload)
            } catch (e: Throwable) {
                reject(callId, e.message ?: "connect failed")
            }
        }
    }

    /** Clear the loopback target; the node + cached sessions stay up. */
    @JavascriptInterface
    fun disconnect(callId: String) {
        worker.execute {
            try {
                Loom.get()?.disconnect()
                resolve(callId, "")
            } catch (e: Throwable) {
                reject(callId, e.message ?: "disconnect failed")
            }
        }
    }

    /**
     * 图片选择（0.14.28 composer 加号键）：source = "camera" | "gallery"。壳侧
     * （MainActivity）拉起相机/Photo Picker，结果经 encodeImagesAsync 编码后
     * resolve {"images":[{dataUrl,name}]}；用户取消 = 空数组（不是错误）。
     */
    @JavascriptInterface
    fun pickImages(callId: String, source: String) {
        onPickImages(callId, source)
    }

    /**
     * 手机本地运行时（0.14.29）：启动/复用打包在 APK 里的完整 vantaloom-api
     * 子进程，resolve {"baseUrl":"http://127.0.0.1:<port>"}。前台服务保活与
     * 组网节点同一个（dataSync）。幂等——已在跑直接返回。
     */
    @JavascriptInterface
    fun startLocalRuntime(callId: String) {
        worker.execute {
            try {
                LoomForegroundService.start(context)
                val port = LocalRuntime.ensureStarted(context)
                resolve(callId, JSONObject().put("baseUrl", "http://127.0.0.1:$port").toString())
            } catch (e: Throwable) {
                reject(callId, e.message ?: "本地运行时启动失败")
            }
        }
    }

    /** Shell-side promise fulfilment (MainActivity 的选择流程用)。 */
    internal fun resolveFromShell(callId: String, payloadJson: String) = resolve(callId, payloadJson)

    internal fun rejectFromShell(callId: String, message: String) = reject(callId, message)

    /**
     * Decode + downscale (long edge ≤ [pickMaxEdge], EXIF 转正) + JPEG q85 +
     * base64 on the worker thread, then resolve callId with
     * {"images":[{dataUrl,name}]}. Undecodable entries are skipped; onDone runs
     * regardless (camera temp-file cleanup).
     */
    internal fun encodeImagesAsync(callId: String, uris: List<Uri>, onDone: () -> Unit = {}) {
        worker.execute {
            try {
                val arr = JSONArray()
                for (uri in uris.take(pickMaxImages)) {
                    val encoded = encodeImage(uri) ?: continue
                    arr.put(encoded)
                }
                resolve(callId, JSONObject().put("images", arr).toString())
            } catch (e: Throwable) {
                reject(callId, e.message ?: "图片处理失败")
            } finally {
                onDone()
            }
        }
    }

    private fun encodeImage(uri: Uri): JSONObject? {
        val resolver = context.contentResolver
        val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
        // 注意：bounds pass 的 decodeStream 返回值恒为 null（inJustDecodeBounds
        // 语义），elvis 必须只兜流打不开，不能兜解码返回值。
        val boundsStream = resolver.openInputStream(uri) ?: return null
        boundsStream.use { BitmapFactory.decodeStream(it, null, bounds) }
        if (bounds.outWidth <= 0 || bounds.outHeight <= 0) return null
        var sample = 1
        while (bounds.outWidth / sample > pickMaxEdge || bounds.outHeight / sample > pickMaxEdge) {
            sample *= 2
        }
        val opts = BitmapFactory.Options().apply { inSampleSize = sample }
        var bitmap = resolver.openInputStream(uri)?.use { BitmapFactory.decodeStream(it, null, opts) }
            ?: return null
        // 相机竖拍靠 EXIF 标方向——不转正会横躺进对话。
        val rotation = readExifRotation(uri)
        if (rotation != 0f) {
            val matrix = Matrix().apply { postRotate(rotation) }
            val rotated = Bitmap.createBitmap(bitmap, 0, 0, bitmap.width, bitmap.height, matrix, true)
            if (rotated !== bitmap) bitmap.recycle()
            bitmap = rotated
        }
        val out = ByteArrayOutputStream()
        bitmap.compress(Bitmap.CompressFormat.JPEG, 85, out)
        bitmap.recycle()
        val b64 = Base64.encodeToString(out.toByteArray(), Base64.NO_WRAP)
        return JSONObject()
            .put("dataUrl", "data:image/jpeg;base64,$b64")
            .put("name", "photo-${System.currentTimeMillis()}.jpg")
    }

    private fun readExifRotation(uri: Uri): Float = try {
        context.contentResolver.openInputStream(uri)?.use { stream ->
            when (
                ExifInterface(stream).getAttributeInt(
                    ExifInterface.TAG_ORIENTATION,
                    ExifInterface.ORIENTATION_NORMAL,
                )
            ) {
                ExifInterface.ORIENTATION_ROTATE_90 -> 90f
                ExifInterface.ORIENTATION_ROTATE_180 -> 180f
                ExifInterface.ORIENTATION_ROTATE_270 -> 270f
                else -> 0f
            }
        } ?: 0f
    } catch (_: Throwable) {
        0f
    }

    /** Tear the node down and stop the foreground service. */
    @JavascriptInterface
    fun stopNode(callId: String) {
        worker.execute {
            try {
                Loom.get()?.stop()
                LoomForegroundService.stop(context)
                resolve(callId, "")
            } catch (e: Throwable) {
                reject(callId, e.message ?: "stop failed")
            }
        }
    }

    /**
     * Fulfil the web-side promise for callId (contract v2). payloadJson is the
     * raw JSON text of the success value ("" for void) — quote() turns it into a
     * JS string literal; the web JSON.parses it. Defensive `&&`: a page reload
     * can race an in-flight worker task, leaving no resolver installed.
     */
    private fun resolve(callId: String, payloadJson: String) {
        evalJs("window.__loomResolve && window.__loomResolve(${quote(callId)}, ${quote(payloadJson)})")
    }

    private fun reject(callId: String, message: String) {
        evalJs("window.__loomReject && window.__loomReject(${quote(callId)}, ${quote(message)})")
    }

    // JSONObject.quote yields a properly escaped JSON string literal, which is also
    // a valid JS string literal.
    private fun quote(s: String): String = JSONObject.quote(s)

    companion object {
        /** 单次最多带回的图片数（Photo Picker 的 EXTRA_PICK_IMAGES_MAX 同值）。 */
        const val pickMaxImages = 6

        /** 长边像素上限——超过按 2 的幂降采样（与桌面端 read 读图口径一致）。 */
        private const val pickMaxEdge = 2048
    }
}
